import React from 'react'
import { useState } from 'react'
import { v4 as uuidv4 } from 'uuid';   //for unique id

// export default function TodoList(){
//     let [todos,setTodos]=useState(["Sample Task"]);
//     let [newTodo,setNewTodo]=useState("");

//     let addNewTask=()=>{
//         setTodos([...todos,newTodo]);
//         setNewTodo("");   //call krke value ko reset kr do
//     };
//     let updateTodoValue=(event)=>{
//       setNewTodo(event.target.value);
//     };



//   return (
//     <div>
//         <input placeholder='Add a Task'  value={newTodo} onChange={updateTodoValue}/>
//         <br /><br />
//         <button onClick={addNewTask}>Add TAsk</button>
//         <br />
//         <br /><br />
//         <h4>Tasks ToDo</h4>
//         {/* todo ko print krne k liye map use kre hai */}
//         <ul>
//             {todos.map((todo)=>(
//                 <li>{todo}</li>
//             ))}
//         </ul>
//     </div>
//   )
// }







// now we store todo with Unique by generated by uuid












// export default function TodoList(){
//   let [todos,setTodos]=useState([{task:"Simple Task",id:uuidv4()}]);   //array of object bnaaye hai
//   let [newTodo,setNewTodo]=useState("");

//   let addNewTask=()=>{
//       setTodos([...todos,{task:newTodo,id:uuidv4()}]);
//       setNewTodo("");   //call krke value ko reset kr do
//   };
//   let updateTodoValue=(event)=>{
//     setNewTodo(event.target.value);
//   };

// let deletTodo=(id)=>{
//   let filteredTodo=todos.filter((todo)=>todo.id != id);
//   setTodos(filteredTodo);
// }

// let uppercaseAll=()=>{
//     let newArr=todos.map((todo)=>{
//         return {
//             ...todo,
//             task:todo.task.toUpperCase(),
//         };
//     })

//     //pass kr do new arr ko print krne k liye
//     setTodos(newArr);
// }


// let UpperCaseOne=(id)=>{
//     setTodos((prevtodos)=>
//     prevtodos.map((todo)=>{
//         if(todo.id==id){
//             return {
//                 ...todo,
//                 task:todo.task.toUpperCase(),
//             };
//         } else {
//             return todo;
//         }
//     })
//     );
// };


// return (
//   <div>
//       <input placeholder='Add a Task'  value={newTodo} onChange={updateTodoValue}/>
//       <br /><br />
//       <button onClick={addNewTask}>Add TAsk</button>
//       <br />
//       <br /><br />
//       <h4>Tasks ToDo</h4>
      
//       <ul>
//           {todos.map((todo)=>(
//               <li key={todo.id}>
//                                         {/* //todo ab object ho gya id aa jane se,so task ko print kro */}
//                 <span>{todo.task}</span>
//                 &nbsp; &nbsp; &nbsp;
//                                     {/* id  pass kr rhe dlt krne ke liye,jb kuch pass krn hota hai to arrow function me pass kro */}
//                 <button onClick={()=>deletTodo(todo.id)}>delte</button>   
//                                       {/* delete means filter lgaa diyehai */}

//              <button onClick={()=>UpperCaseOne(todo.id)}>Uppercase one</button>   
//                 </li>  
//           ))}
//       </ul>

//       <hr />


//       <button onClick={uppercaseAll}>Convert Into uppercase</button>
//   </div>
// )
// }












 //isDone v functionaliye laayenge,
//  uppercaseone ->markasdone me change krenge beacause uppercase me change krne ke wajaaye isDone=true krnege



 export default function TodoList(){
    let [todos,setTodos]=useState([{task:"Simple Task",id:uuidv4(),isDone:false}]);   //array of object bnaaye hai
    let [newTodo,setNewTodo]=useState("");
  
    let addNewTask=()=>{
        setTodos([...todos,{task:newTodo,id:uuidv4()}]);
        setNewTodo("");   //call krke value ko reset kr do
    };
    let updateTodoValue=(event)=>{
      setNewTodo(event.target.value);
    };
  
  let deletTodo=(id)=>{
    let filteredTodo=todos.filter((todo)=>todo.id != id);
    setTodos(filteredTodo);
  }
  
  let markAllDone=()=>{
      let newArr=todos.map((todo)=>{
          return {
              ...todo,
              isDone:true,
          };
      })
  
      //pass kr do new arr ko print krne k liye
      setTodos(newArr);
  }
  
  
                // isDone ki value true hone pe style chnage hoga
  let markAsDone=(id)=>{
      setTodos((prevtodos)=>
      prevtodos.map((todo)=>{
          if(todo.id==id){
              return {
                  ...todo,
                  isDone:true,        //false se true krdo then kuch style apply hoga
              };
          } else {
              return todo;
          }
      })
      );
  };
  
  
  return (
    <div>
        <input placeholder='Add a Task'  value={newTodo} onChange={updateTodoValue}/>
        <br /><br />
        <button onClick={addNewTask}>Add TAsk</button>
        <br />
        <br /><br />
        <h4>Tasks ToDo</h4>
        
        <ul>
            {todos.map((todo)=>(
                                //  style me isdone true hone pe style lgega
                <li style={todo.isDone?{textDecorationLine:'line-through'}:{}} key={todo.id}>
                                          {/* //todo ab object ho gya id aa jane se,so task ko print kro */}
                  <span>{todo.task}</span>
                  &nbsp; &nbsp; &nbsp;
                                      {/* id  pass kr rhe dlt krne ke liye,jb kuch pass krn hota hai to arrow function me pass kro */}
                  <button onClick={()=>deletTodo(todo.id)}>delte</button>   
                                        {/* delete means filter lgaa diyehai */}
  
               
               <button onClick={()=>markAsDone(todo.id)}>MArk As Done</button>   
                  </li>  
            ))}
        </ul>
  
        <hr />
  
  
        <button onClick={markAllDone}>MArk All as Done</button>
    </div>
  )
  }
  